In [1]:
import numpy as np

# Logistic Regression Module

In [2]:
class LogisticRegression():
    def __init__(self,eta = 0.01,max_iterations = 100000,desired_acccuracy = 100,tolerance = 1e-5):
        self.learning_rate = eta                      #learning_rate
        self.max_iterations = max_iterations          
        self.iter = 0
        self.cost_record = np.zeros(max_iterations)   #cost record for no significant change
        self.desired_acccuracy = desired_acccuracy    #accuracy to be achived
        self.tolerance = tolerance
    def fit(self,X,y):
        self.X = self.expand_column(X)                #add columns of 1 to mutiply with bias
        self.actual_y = y
        y = y.reshape(-1,1)                           #convert into 2d
        self.y = y
        weight_length = self.X.shape[1]
        self.thetas = np.random.rand(weight_length,1) #initailize weights
        self.learning()
    def sigmoid(self,X):
        z = np.dot(X,self.thetas)
        sig_z = 1 / (1 + np.exp(-z))
        return sig_z
    def cost(self):
        m = self.X.shape[0]
        ho = self.sigmoid(self.X)
        cost = (1/m) * (-np.dot(self.y.T, np.log(ho+1e-10)) - np.dot((1 - self.y).T, np.log(1 - ho+1e-10)))
        return cost[0][0]
    def gradient(self):
        m = self.X.shape[0]
        ho = self.sigmoid(self.X)
        self.thetas -= (self.learning_rate/m) * np.dot(self.X.T, (ho-self.y))
    def learning(self):
        """
        Three conditions to stop
        1) No.of iterations
        2) Desired Accuracy achived
        3) No significant change occur
        """
        while self.iter < self.max_iterations:
            accuracy = self._accuracy(self.X,self.actual_y)
            cost = self.cost()
            self.cost_record[self.iter] = cost
            if accuracy >= self.desired_acccuracy:
                print("Accuracy achieved")
                break
            elif self.iter != 0 and np.abs(self.cost_record[self.iter] - self.cost_record[self.iter-1]) <= self.tolerance:
                print("No significant changes occur")
                break
            self.gradient()
            self.iter += 1
    def predict(self,X):
        X = self.expand_column(X)
        return self._predicted(X)
    def _predicted(self,X):
        z = self.sigmoid(X)
        y = np.where(z>=0.5,1,0)
        return y.flatten()
    def accuracy(self,X,y):
        X = self.expand_column(X)
        return self._accuracy(X,y)
        
    def _accuracy(self,X,y):
        y_pred = self._predicted(X)
        accuracy = np.mean(y==y_pred)
        return accuracy * 100
        
    def expand_column(self,X):
        col = np.ones(X.shape[0])
        col = col.reshape(-1,1)
        X = np.hstack((col,X))
        return X
        
    

# AND Gate

In [3]:
X = np.array([
    [0,0],
    [0,1],
    [1,0],
    [1,1]
])
y = np.array([0,0,0,1])
X,y

(array([[0, 0],
        [0, 1],
        [1, 0],
        [1, 1]]),
 array([0, 0, 0, 1]))

In [4]:
obj = LogisticRegression()
obj.fit(X,y)

Accuracy achieved


In [5]:
pred = obj.predict(X)

In [6]:
pred

array([0, 0, 0, 1])

In [7]:
weights = obj.thetas
weights

array([[-0.59292436],
       [ 0.59196515],
       [ 0.57074797]])

In [8]:
print("Accuarcy",obj.accuracy(X,y))

Accuarcy 100.0


# OR Gate

In [9]:
X = np.array([
    [0,0],
    [0,1],
    [1,0],
    [1,1]
])
y = np.array([0,1,1,1])
X,y

(array([[0, 0],
        [0, 1],
        [1, 0],
        [1, 1]]),
 array([0, 1, 1, 1]))

In [10]:
obj = LogisticRegression()
obj.fit(X,y)

Accuracy achieved


In [11]:
pred = obj.predict(X)
pred

array([0, 1, 1, 1])

In [12]:
weights = obj.thetas
weights

array([[-7.57359991e-05],
       [ 1.65568850e+00],
       [ 1.65587534e+00]])

In [13]:
print("Accuarcy",obj.accuracy(X,y))

Accuarcy 100.0


## OCR

In [14]:
X_train = np.loadtxt('trainX.txt')
y_train = np.loadtxt('trainY.txt')
X_train.shape,y_train.shape


((500, 256), (500,))

In [15]:
X_test = np.loadtxt('testX.txt')
y_test = np.loadtxt('testY.txt')
X_test.shape,y_test.shape

((100, 256), (100,))

In [16]:
y_train = np.where(y_train == 2,0,1)        #assign one class as 0 and other is 1 because i define a class for 0 and 1
y_test = np.where(y_test == 2,0,1)   

## learning_rate = 0.1

In [17]:
obj_1 = LogisticRegression(eta=0.1,desired_acccuracy=90)
obj_1.fit(X_train,y_train)

Accuracy achieved


In [18]:
pre_training_data = obj_1.predict(X_train)

In [19]:
print("Accuracy on training data : ",obj_1.accuracy(X_train,y_train))

Accuracy on training data :  90.0


In [20]:
pre_testing_data = obj_1.predict(X_test)

In [21]:
print("Accuracy on training data : ",obj_1.accuracy(X_test,y_test))

Accuracy on training data :  98.0


## learning rate 0.01

In [22]:
obj_2 = LogisticRegression(eta=0.01,desired_acccuracy=90)
obj_2.fit(X_train,y_train)

Accuracy achieved


In [23]:
pre_training_data = obj_2.predict(X_train)

In [24]:
print("Accuracy on training data : ",obj_2.accuracy(X_train,y_train))

Accuracy on training data :  90.0


In [25]:
pre_testing_data = obj_2.predict(X_test)

In [26]:
print("Accuracy on training data : ",obj_2.accuracy(X_test,y_test))

Accuracy on training data :  99.0


## learning rate 0.001

In [27]:
obj_3 = LogisticRegression(eta=0.001,desired_acccuracy=90)
obj_3.fit(X_train,y_train)

Accuracy achieved


In [28]:
pre_training_data = obj_3.predict(X_train)

In [29]:
print("Accuracy on training data : ",obj_3.accuracy(X_train,y_train))

Accuracy on training data :  90.0


In [30]:
pre_testing_data = obj_3.predict(X_test)

In [31]:
print("Accuracy on training data : ",obj_3.accuracy(X_test,y_test))

Accuracy on training data :  99.0
